{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10e67949",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "[2021-10-01 14:44:52,135] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3141, in _wrap_pool_connect\n",
      "    return fn()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 301, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 755, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 419, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 145, in _do_get\n",
      "    self._dec_overflow()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 70, in __exit__\n",
      "    compat.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 142, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 247, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 362, in __init__\n",
      "    self.__connect(first_connect_check=True)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 605, in __connect\n",
      "    pool.logger.debug(\"Error on connect(): %s\", e)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 70, in __exit__\n",
      "    compat.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 599, in __connect\n",
      "    connection = pool._invoke_creator(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 578, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 559, in connect\n",
      "    return self.dbapi.connect(*cargs, **cparams)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 353, in __init__\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 633, in connect\n",
      "    self._request_authentication()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 907, in _request_authentication\n",
      "    auth_packet = self._read_packet()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 725, in _read_packet\n",
      "    packet.raise_for_error()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n",
      "    err.raise_mysql_exception(self._data)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n",
      "    raise errorclass(errno, errval)\n",
      "pymysql.err.OperationalError: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-9d63171df8db>\", line 74, in home\n",
      "    db.session.commit()\n",
      "  File \"<string>\", line 2, in commit\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 1423, in commit\n",
      "    self._transaction.commit(_to_root=self.future)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 829, in commit\n",
      "    self._prepare_impl()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 808, in _prepare_impl\n",
      "    self.session.flush()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 3241, in flush\n",
      "    self._flush(objects)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 3381, in _flush\n",
      "    transaction.rollback(_capture_exception=True)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 70, in __exit__\n",
      "    compat.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 3341, in _flush\n",
      "    flush_context.execute()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 453, in execute\n",
      "    rec.execute(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 627, in execute\n",
      "    util.preloaded.orm_persistence.save_obj(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 209, in save_obj\n",
      "    for (\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 370, in _organize_states_for_save\n",
      "    for state, dict_, mapper, connection in _connections_for_states(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 1709, in _connections_for_states\n",
      "    connection = uowtransaction.transaction.connection(base_mapper)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 626, in connection\n",
      "    return self._connection_for_bind(bind, execution_options)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 735, in _connection_for_bind\n",
      "    conn = self._parent._connection_for_bind(bind, execution_options)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 747, in _connection_for_bind\n",
      "    conn = bind.connect()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3095, in connect\n",
      "    return self._connection_cls(self, close_with_result=close_with_result)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 91, in __init__\n",
      "    else engine.raw_connection()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3174, in raw_connection\n",
      "    return self._wrap_pool_connect(self.pool.connect, _connection)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3144, in _wrap_pool_connect\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2003, in _handle_dbapi_exception_noconnection\n",
      "    util.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3141, in _wrap_pool_connect\n",
      "    return fn()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 301, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 755, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 419, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 145, in _do_get\n",
      "    self._dec_overflow()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 70, in __exit__\n",
      "    compat.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 142, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 247, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 362, in __init__\n",
      "    self.__connect(first_connect_check=True)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 605, in __connect\n",
      "    pool.logger.debug(\"Error on connect(): %s\", e)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 70, in __exit__\n",
      "    compat.raise_(\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 599, in __connect\n",
      "    connection = pool._invoke_creator(self)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 578, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 559, in connect\n",
      "    return self.dbapi.connect(*cargs, **cparams)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 353, in __init__\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 633, in connect\n",
      "    self._request_authentication()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 907, in _request_authentication\n",
      "    auth_packet = self._read_packet()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\connections.py\", line 725, in _read_packet\n",
      "    packet.raise_for_error()\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n",
      "    err.raise_mysql_exception(self._data)\n",
      "  File \"C:\\Users\\chahn\\anaconda3\\lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n",
      "    raise errorclass(errno, errval)\n",
      "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")\n",
      "(Background on this error at: http://sqlalche.me/e/14/e3q8)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [01/Oct/2021 14:44:52] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import pymysql\n",
    "from flask import Flask, render_template\n",
    "# 필요한 모듈들을 import합니다.\n",
    "import enum\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "db = SQLAlchemy()\n",
    "\n",
    "class OrderMethod(enum.Enum):\n",
    "    card = \"card\"\n",
    "    cash = \"cash\"\n",
    "\n",
    "# 지시사항 1번을 참고하여 코드를 작성하세요.\n",
    "class User(db.Model):\n",
    "    id = db.Column(db.String(10), primary_key= True)\n",
    "    delivery_address =db.Column(db.String(100), nullable=False)\n",
    "    order_method = db.Column(db.Enum(OrderMethod), nullable=False)\n",
    "    \n",
    "    def __init__(self, id, delivery_address, order_method):\n",
    "        self.id = id\n",
    "        self.delivery_address = delivery_address\n",
    "        self.order_method = order_method\n",
    "\n",
    "class Store(db.Model):\n",
    "    id =db.Column(db.String(30), primary_key= True)\n",
    "    store_address = db.Column(db.String(100), nullable=False)\n",
    "    contact_number = db.Column(db.String(14), nullable=False)\n",
    "    \n",
    "    def __init__(self, id, store_address, contact_number):\n",
    "        self.id = id\n",
    "        self.store_address = store_address\n",
    "        self.contact_number = contact_number\n",
    "\n",
    "class DeliveryOrder(db.Model):\n",
    "    id = db.Column(db.Integer, primary_key=True, autoincrement=True)\n",
    "    user_id = db.Column(db.String(10), nullable=False)\n",
    "    store_id = db.Column(db.String(30), nullable=False)\n",
    "    total_price = db.Column(db.Integer, nullable=False)\n",
    "    delivery_fee =db.Column(db.Integer, nullable=False)\n",
    "    order_dt = db.Column(db.DateTime, nullable=False)\n",
    "    order_method = db.Column(db.Enum(OrderMethod), nullable=False)\n",
    "    delivery_address = db.Column(db.String(100), nullable=False)\n",
    "\n",
    "    def __init__(self, user_id, store_id, total_price, delivery_fee, order_method, delivery_address):\n",
    "        self.user_id = user_id\n",
    "        self.store_id = store_id\n",
    "        self.total_price = total_price\n",
    "        self.delivery_fee = delivery_fee\n",
    "        self.order_method = order_method\n",
    "        self.delivery_address = delivery_address\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = \"mysql+pymysql://root:devpass@127.0.0.1:3306/elice_flask_board\"\n",
    "app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False \n",
    "\n",
    "db.init_app(app)\n",
    "\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    user_id = \"elice\"\n",
    "    order_method = \"card\"\n",
    "    delivery_address = \"서울특별시 강남구\"\n",
    "    user = User(user_id, delivery_address, order_method)\n",
    "    db.session.add(user)\n",
    "\n",
    "    store_id = \"엘리스 떡볶이\"\n",
    "    store = Store(store_id, \"서울특별시 강남구\", \"02-1234-5678\")\n",
    "    db.session.add(store)\n",
    "\n",
    "    # 지시사항 2번을 참고하여 코드를 작성하세요.\n",
    "    order = DeliveryOrder(user_id, store_id, 13000, 3000, order_method, delivery_address)\n",
    "    db.session.add(order)\n",
    "    db.session.commit()\n",
    "\n",
    "    return \"ok\"\n",
    "\n",
    "\n",
    "@app.route(\"/orders\")\n",
    "def orders():\n",
    "    # 지시사항 3번을 참고하여 코드를 작성하세요.\n",
    "    data = DeliveryOrder.query.all()\n",
    "    \n",
    "    orders = [\n",
    "        {\n",
    "            'user_id':d.user_id,\n",
    "            'store_id':d.store_id,\n",
    "            'total_price':d.total_price,\n",
    "            'delivery_fee':d.delivery_fee,\n",
    "            'order_method':d.order_method.value,\n",
    "            'delivery_address':d.delivery_address,\n",
    "        }\n",
    "        for d in data\n",
    "    ]\n",
    "\n",
    "    return render_template('orders.html', orders=orders)\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9513f95b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
